package com.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.greendaodemo2.MovieCollect;
import com.greendaodemo2.User;

import com.greendao.db.MovieCollectDao;
import com.greendao.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig movieCollectDaoConfig;
    private final DaoConfig userDaoConfig;

    private final MovieCollectDao movieCollectDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        movieCollectDaoConfig = daoConfigMap.get(MovieCollectDao.class).clone();
        movieCollectDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        movieCollectDao = new MovieCollectDao(movieCollectDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(MovieCollect.class, movieCollectDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        movieCollectDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public MovieCollectDao getMovieCollectDao() {
        return movieCollectDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
